version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/initial"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/initial"
    schedule:
      interval: "monthly"
    target-branch: "main"


  # - package-ecosystem: "maven"
  #   directory: "/initial/bookstore/"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"

  # - package-ecosystem: "gradle"
  #   directory: "/initial/bookstore/" 
  #   ignore:
  #     - dependency-name: "org.springframework.*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"

  # - package-ecosystem: "maven"
  #   directory: "/initial/reading/"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"

  # - package-ecosystem: "gradle"
  #   directory: "/initial/reading/" 
  #   ignore:
  #     - dependency-name: "org.springframework.*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"


  # - package-ecosystem: "maven"
  #   directory: "/complete/bookstore/"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"

  # - package-ecosystem: "gradle"
  #   directory: "/complete/bookstore/" 
  #   ignore:
  #     - dependency-name: "org.springframework.*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"

  # - package-ecosystem: "maven"
  #   directory: "/complete/reading/"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"

  # - package-ecosystem: "gradle"
  #   directory: "/complete/reading/" 
  #   ignore:
  #     - dependency-name: "org.springframework.*"
  #       update-types: ["version-update:semver-patch"]
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "main"
    
    
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
