version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/" 
    ignore:
      - dependency-name: "org.springframework.*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
